# code: language=ansible
---
- name: Install Oh My Zsh
  ansible.builtin.import_tasks: install.yml

- name: Console setup for Debian family distributions
  ansible.builtin.include_tasks: debian-console-setup.yml
  when: ansible_os_family == 'Debian'
