---
- name: install git
  become: yes
  apt:
    name: git
    state: present

- name: install zsh
  become: yes
  apt:
    name: zsh
    state: present

- name: clone oh-my-zsh for users
  become: yes
  # core.autocrlf=input prevents https://github.com/robbyrussell/oh-my-zsh/issues/4402
  command: "git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git ~{{ item.username }}/.oh-my-zsh"
  args:
    creates: "~{{ item.username }}/.oh-my-zsh"
  with_items: "{{ users }}"

- name: set ownership and permissions of oh-my-zsh for users
  become: yes
  file:
    path: "~{{ item.username }}/.oh-my-zsh"
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    # Prevent the cloned repository from having insecure permissions. Failing to do
    # so causes compinit() calls to fail with "command not found: compdef" errors
    # for users with insecure umasks (e.g., "002", allowing group writability).
    mode: 'go-w'
    recurse: yes
  with_items: "{{ users }}"

- name: set default shell for users
  become: yes
  user:
    name: "{{ item.username }}"
    shell: /bin/zsh
  with_items: "{{ users }}"

- name: write .zshrc for users
  become: yes
  become_user: "{{ item.username }}"
  template:
    src: zshrc.j2
    dest: '~{{ item.username }}/.zshrc'
    backup: yes
    mode: 'u=rw,go=r'
  with_items: "{{ users }}"
