# code: language=ansible
---
- name: Setting OS variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.os_family }}.yml"
        - default.yml
      paths:
        - vars/os_family

- name: Install dependencies
  become: "{{ ansible_facts.distribution != 'MacOSX' }}"
  ansible.builtin.package:
    name: "{{ oh_my_zsh_dependencies }}"
    state: present

- name: Install Oh My Zsh
  ansible.builtin.include_tasks: install.yml
  vars:
    oh_my_zsh: "{{ user.oh_my_zsh | default(oh_my_zsh_defaults) }}"
  when: oh_my_zsh.install | default(oh_my_zsh_install) | bool
  loop: "{{ users | flatten(levels=1) }}"
  loop_control:
    loop_var: user
    label: "{{ user.name }}"

- name: Console setup for Debian family distributions
  ansible.builtin.include_tasks: debian-console-setup.yml
  when: ansible_facts.os_family == 'Debian'
