# code: language=ansible
---
- name: Converge
  hosts: all

  pre_tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts.os_family == 'Debian'
      changed_when: false

    - name: Create test users
      become: true
      ansible.builtin.user:
        name: '{{ item }}'
        home: '/home/{{ item }}'
        createhome: true
      with_items:
        - test_usr1
        - test_usr2
        - test_usr3
        - test_usr4
        - test_usr5
        - test_usr6

    - name: Install console-setup file
      become: true
      ansible.builtin.copy:
        src: tests/console-setup.sh
        dest: /etc/default/console-setup
        force: false
        owner: root
        group: root
        mode: 'u=rwx,go=r'

  roles:
    - role: ansible-role-oh-my-zsh
      oh_my_zsh_theme: test_theme1
      oh_my_zsh_plugins:
        - test_plugin1
        - test_plugin2
      users:
        - username: test_usr1
        - username: test_usr2
          oh_my_zsh:
            theme: test_theme2
            plugins:
              - test_plugin3
              - test_plugin4
            update_mode: auto
            update_frequency: 31
        - username: test_usr3
          oh_my_zsh:
            install: false
        - username: test_usr4
          oh_my_zsh:
            write_zshrc: false

    - role: ansible-role-oh-my-zsh
      oh_my_zsh_theme: test_theme1
      oh_my_zsh_plugins:
        - test_plugin1
        - test_plugin2
      oh_my_zsh_install: false
      oh_my_write_zshrc: false
      users:
        - username: test_usr5
        - username: test_usr6
          oh_my_zsh:
            install: true
            write_zshrc: true
            theme: test_theme2
            plugins:
              - test_plugin3
              - test_plugin4
