---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-oh-my-zsh-debian-min
    image: debian:7
  - name: ansible-role-oh-my-zsh-debian-max
    image: debian:8
  - name: ansible-role-oh-my-zsh-ubuntu-min
    image: ubuntu:14.04
  - name: ansible-role-oh-my-zsh-ubuntu-max
    image: ubuntu:18.04
  - name: ansible-role-oh-my-zsh-centos
    image: centos:7
  - name: ansible-role-oh-my-zsh-fedora
    image: fedora:25
  - name: ansible-role-oh-my-zsh-opensuse
    image: opensuse:42.2

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
